/*
 * Parking Spot Api REST
 * API REST for parking spot control.
 *
 * OpenAPI spec version: 1.0
 * Contact: marcus.quintela@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
