/*
 * Parking Spot Api REST
 * API REST for parking spot control.
 *
 * OpenAPI spec version: 1.0
 * Contact: marcus.quintela@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;
import org.threeten.bp.OffsetDateTime;

/**
 * ParkingSpotModel
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2022-02-25T17:12:46.932Z")
public class ParkingSpotModel {
  @SerializedName("apartament")
  private String apartament = null;

  @SerializedName("block")
  private String block = null;

  @SerializedName("brandCar")
  private String brandCar = null;

  @SerializedName("colorCar")
  private String colorCar = null;

  @SerializedName("id")
  private UUID id = null;

  @SerializedName("licensePlateCar")
  private String licensePlateCar = null;

  @SerializedName("modelCar")
  private String modelCar = null;

  @SerializedName("parkingSpotNumber")
  private String parkingSpotNumber = null;

  @SerializedName("registratorDate")
  private OffsetDateTime registratorDate = null;

  @SerializedName("responsibleName")
  private String responsibleName = null;

  public ParkingSpotModel apartament(String apartament) {
    this.apartament = apartament;
    return this;
  }

   /**
   * Get apartament
   * @return apartament
  **/
  @ApiModelProperty(value = "")
  public String getApartament() {
    return apartament;
  }

  public void setApartament(String apartament) {
    this.apartament = apartament;
  }

  public ParkingSpotModel block(String block) {
    this.block = block;
    return this;
  }

   /**
   * Get block
   * @return block
  **/
  @ApiModelProperty(value = "")
  public String getBlock() {
    return block;
  }

  public void setBlock(String block) {
    this.block = block;
  }

  public ParkingSpotModel brandCar(String brandCar) {
    this.brandCar = brandCar;
    return this;
  }

   /**
   * Get brandCar
   * @return brandCar
  **/
  @ApiModelProperty(value = "")
  public String getBrandCar() {
    return brandCar;
  }

  public void setBrandCar(String brandCar) {
    this.brandCar = brandCar;
  }

  public ParkingSpotModel colorCar(String colorCar) {
    this.colorCar = colorCar;
    return this;
  }

   /**
   * Get colorCar
   * @return colorCar
  **/
  @ApiModelProperty(value = "")
  public String getColorCar() {
    return colorCar;
  }

  public void setColorCar(String colorCar) {
    this.colorCar = colorCar;
  }

  public ParkingSpotModel id(UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public UUID getId() {
    return id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public ParkingSpotModel licensePlateCar(String licensePlateCar) {
    this.licensePlateCar = licensePlateCar;
    return this;
  }

   /**
   * Get licensePlateCar
   * @return licensePlateCar
  **/
  @ApiModelProperty(value = "")
  public String getLicensePlateCar() {
    return licensePlateCar;
  }

  public void setLicensePlateCar(String licensePlateCar) {
    this.licensePlateCar = licensePlateCar;
  }

  public ParkingSpotModel modelCar(String modelCar) {
    this.modelCar = modelCar;
    return this;
  }

   /**
   * Get modelCar
   * @return modelCar
  **/
  @ApiModelProperty(value = "")
  public String getModelCar() {
    return modelCar;
  }

  public void setModelCar(String modelCar) {
    this.modelCar = modelCar;
  }

  public ParkingSpotModel parkingSpotNumber(String parkingSpotNumber) {
    this.parkingSpotNumber = parkingSpotNumber;
    return this;
  }

   /**
   * Get parkingSpotNumber
   * @return parkingSpotNumber
  **/
  @ApiModelProperty(value = "")
  public String getParkingSpotNumber() {
    return parkingSpotNumber;
  }

  public void setParkingSpotNumber(String parkingSpotNumber) {
    this.parkingSpotNumber = parkingSpotNumber;
  }

  public ParkingSpotModel registratorDate(OffsetDateTime registratorDate) {
    this.registratorDate = registratorDate;
    return this;
  }

   /**
   * Get registratorDate
   * @return registratorDate
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getRegistratorDate() {
    return registratorDate;
  }

  public void setRegistratorDate(OffsetDateTime registratorDate) {
    this.registratorDate = registratorDate;
  }

  public ParkingSpotModel responsibleName(String responsibleName) {
    this.responsibleName = responsibleName;
    return this;
  }

   /**
   * Get responsibleName
   * @return responsibleName
  **/
  @ApiModelProperty(value = "")
  public String getResponsibleName() {
    return responsibleName;
  }

  public void setResponsibleName(String responsibleName) {
    this.responsibleName = responsibleName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ParkingSpotModel parkingSpotModel = (ParkingSpotModel) o;
    return Objects.equals(this.apartament, parkingSpotModel.apartament) &&
        Objects.equals(this.block, parkingSpotModel.block) &&
        Objects.equals(this.brandCar, parkingSpotModel.brandCar) &&
        Objects.equals(this.colorCar, parkingSpotModel.colorCar) &&
        Objects.equals(this.id, parkingSpotModel.id) &&
        Objects.equals(this.licensePlateCar, parkingSpotModel.licensePlateCar) &&
        Objects.equals(this.modelCar, parkingSpotModel.modelCar) &&
        Objects.equals(this.parkingSpotNumber, parkingSpotModel.parkingSpotNumber) &&
        Objects.equals(this.registratorDate, parkingSpotModel.registratorDate) &&
        Objects.equals(this.responsibleName, parkingSpotModel.responsibleName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apartament, block, brandCar, colorCar, id, licensePlateCar, modelCar, parkingSpotNumber, registratorDate, responsibleName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ParkingSpotModel {\n");
    
    sb.append("    apartament: ").append(toIndentedString(apartament)).append("\n");
    sb.append("    block: ").append(toIndentedString(block)).append("\n");
    sb.append("    brandCar: ").append(toIndentedString(brandCar)).append("\n");
    sb.append("    colorCar: ").append(toIndentedString(colorCar)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    licensePlateCar: ").append(toIndentedString(licensePlateCar)).append("\n");
    sb.append("    modelCar: ").append(toIndentedString(modelCar)).append("\n");
    sb.append("    parkingSpotNumber: ").append(toIndentedString(parkingSpotNumber)).append("\n");
    sb.append("    registratorDate: ").append(toIndentedString(registratorDate)).append("\n");
    sb.append("    responsibleName: ").append(toIndentedString(responsibleName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

